dist: xenial
before_install:
  - sudo apt-get install lsb-release -y
  - wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
  - sudo dpkg -i cvmfs-release-latest_all.deb
  - sudo rm -f cvmfs-release-latest_all.deb
  - sudo apt-get update -q
  - sudo apt-get install cvmfs cvmfs-config-default -y

jobs:
 include:
   - script: sudo sh ./mount.sh > ./current/mount.log && sudo sh ./modify.sh > ./current/modify.log && sudo sh ./push.sh
