dist: xenial
before_install:
  - sudo apt-get install lsb-release -y
  - wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
  - sudo dpkg -i cvmfs-release-latest_all.deb
  - sudo rm -f cvmfs-release-latest_all.deb
  - sudo apt-get update -q
  - sudo apt-get install cvmfs cvmfs-config-default -y

jobs:
 include:
   - script: travis_wait 50 sudo sh ./mount.sh && sudo sh ./modify.sh && sudo sh ./push.sh
